repos:
  - repo: local
    hooks:
      - id: crystal-format
        name: Check Patchy Formatting (crystal tool format --check)
        entry: crystal tool format --check
        language: system
        types: [crystal]
      - id: ameba-lint
        name: Run Ameba Linter (ameba)
        entry: ameba
        language: system
        types: [crystal]
