services:
  patchy:
    image: git.nadeko.net/fijxu/patchy:latest
    # This program should never use that many memory and more than 50% of the CPU
    mem_limit: 512MB
    cpus: 0.5
    # If you want to use a custom config file, you can mount it here.
    volumes:
      # You need to create the data folder first:
      # mkdir ./data && sudo chown -R 10000:10000 ./data
      - ./data:/data
    ports:
      - 8080:8080

