name: 'File-uploader-crystal CI'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 0'
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: runner

    steps:
    - uses: https://code.forgejo.org/actions/checkout@v2

    - uses: https://code.forgejo.org/docker/setup-buildx-action@v3
      name: Setup Docker BuildX system

    - name: Login to Docker Container Registry
      uses: https://code.forgejo.org/docker/login-action@v3.4.0
      with:
        registry: git.nadeko.net
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Docker meta
      id: meta
      uses: https://code.forgejo.org/docker/metadata-action@v5
      with:
        images: git.nadeko.net/fijxu/file-uploader-crystal
        tags: |
          type=sha,format=short,prefix={{date 'YYYY.MM.DD'}}-,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    - name: Cache .o files for compilation
      uses: https://code.forgejo.org/actions/cache@v4
      id: cache
      with:
        path: |
          codegen-cache
        key: cache-${{ hashFiles('./Dockerfile') }}

    - name: Inject cache into Docker
      uses: https://github.com/reproducible-containers/buildkit-cache-dance@v3.1.0
      with:
        cache-map: |
          {
            "codegen-cache": "/root/.cache/crystal"
          }
        skip-extraction: ${{ steps.cache.outputs.cache-hit }}

    - uses: https://code.forgejo.org/docker/build-push-action@v6
      name: Build images
      with:
        context: .
        file: Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        platforms: linux/amd64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
