colorize_logs: true
# Levels are: none, fatal, error, warn, notice, info, debug and trace
log_level: "debug"

# File paths, you generally don't need to change this
files: "./data/files/"
thumbnails: "./data/thumbnails/"
db: "./data/db/"

# http server
server:
  port: 8080
  host: 0.0.0.0
  # Enabling the unix socket will disable port binding
  #unix_socket: "/tmp/patchy.sock"

thumbnail_generation:
  enabled: false

# To restrict Tor exit nodes and VPN providers IP addresses from uploading
# content to the uploader. Sometimes they can be an annoyance, legally speaking.
ip_block:
  tor:
    enabled: false
    update_interval: 3600
  vpn:
    enabled: false
    update_interval: 86400
    # Providers supported:
    # "Mullvad", "AirVPN"
    providers: []

admin_enabled: true
admin_api_key: "asd"
size_limit: 512
enable_checksums: false

files_per_ip: 2
rate_limit_period: 20
filename_length: 3

# In hours (168 = 7 days)
delete_files_after: 168
# In seconds
delete_files_check: 1800
delete_key_length: 4

site_info: "Whatever you want to put here"
site_warning: "WARNING!"

# S3 Support to upload the files to a S3 bucket.
# Thumbnail generation will not run when using a S3 bucket
s3:
  enabled: false
  # Ignored if is not AWS
  region: us-east-1
  key: "key"
  secret: "secret"
  endpoint: "https://someendpoint.example"

# Uses more memory, but improves files retrieval and reduces stress on the drive
cache:
  enabled: false
  # Number of files that can be cached
  max_size: 256
  # In KiB, files bigger than this will not be cached
  max_allowed_filesize: 512

# Modify what is show on the index index page
views:
  site_info: "Welcome to Patchy - A temporary file uploader"
  show_title: true
  show_file_count: true
  show_version: true
  index_navbar:
    enabled: true
    show_uploader_configs: true
    show_upload_history: true
    show_admin: true
    show_login: true
  autoplay_video: false
  autoplay_audio: false

blocked_extensions:
  - "exe"

# alternative_domains:
#   - "example.com"
