files: "./files"
thumbnails: "./thumbnails"
generateThumbnails: false
db: "./db.sqlite3"
dbTableName: "files"
adminEnabled: true
adminApiKey: "asd"
fileameLength: 3
# In MiB
size_limit: 512
port: 8080
blockTorAddresses: true
# Every hour
torExitNodesCheck: 3600
torExitNodesUrl: "https://www.dan.me.uk/torlist/?exit"
torExitNodesFile: "./torexitnodes.txt"
torMessage: "TOR IS BLOCKED!"
filesPerIP: 2
ipTableName: "ips"
rateLimitPeriod: 20
rateLimitMessage: ""
# If you define the unix socket, it will only listen on the socket and not the port.
#unix_socket: "/tmp/file-uploader.sock"
# In days
deleteFilesAfter: 7
# In seconds
deleteFilesCheck: 1800
deleteKeyLength: 4
siteInfo: "Whatever you want to put here"
siteWarning: "WARNING!"
log_level: "debug"

blockedExtensions:
  - "exe"

# List of useragents that use OpenGraph to gather file information
opengraphUseragents:
  - "chatterino-api-cache/"
  - "FFZBot/"
  - "Twitterbot/"

alternativeDomains: 
  - "ayaya.beauty"
  - "lamartina.gay"
