files: "./files"
thumbnails: "./thumbnails"
generate_thumbnails: false
db: "./db.sqlite3"
db_table_name: "files"
filename_length: 3
# In MiB
size_limit: 512
port: 8080
# If you define the unix socket, it will only listen on the socket and not the port.
#unix_socket: "/tmp/file-uploader.sock"
# In days
delete_files_after: 7
# In seconds
delete_files_after_check_seconds: 1800
delete_key_length: 4
siteInfo: "Whatever you want to put here"
siteWarning: "WARNING!"
log_level: "debug"

blocked_extensions:
  - "exe"
