colorize_logs: true
log_level: "debug"

# File paths, you generally don't need to change this
files: "./data/files/"
thumbnails: "./data/thumbnails/"
db: "./data/db/"

# http server
host: 0.0.0.0
port: 8080
# Enabling the unix socket will disable port binding
#unix_socket: "/tmp/file-uploader.sock"

# Tor
block_tor_addresses: true
tor_exit_nodes_check: 1600
tor_exit_nodes_url: "https://check.torproject.org/exit-addresses"
tor_message: "TOR IS BLOCKED!"

generate_thumbnails: true
admin_enabled: true
admin_api_key: "asd"
size_limit: 512
enable_checksums: false
files_per_ip: 2
rate_limit_period: 20
rate_limit_message: ""
filename_length: 3

# In hours (168 = 7 days)
delete_files_after: 168
# In seconds
delete_files_check: 1800

delete_key_length: 4

site_info: "Whatever you want to put here"
site_warning: "WARNING!"

# Uses more memory, but improves files retrieval and reduces stress on the drive
cache:
  enable: false
  # Number of files that can be cached
  max_size: 256
  # In KiB, files bigger than this will not be cached
  max_allowed_filesize: 512

blocked_extensions:
  - "exe"

opengraph_useragents:
  - "chatterino-api-cache/"
  - "FFZBot/"
  - "Twitterbot/"
  - "Synapse/"
  - "Mastodon/"

# alternative_domains:
#   - "example.com"
