colorize_logs: true
# Levels are: none, fatal, error, warn, notice, info, debug and trace
log_level: "info"

# File paths, you generally don't need to change this
storage:
  files: "./data/files/"
  thumbnails: "./data/thumbnails/"
  db: "./data/db/"

# Rate limit uploads per IP address
rate_limits:
  enabled: false
  # How many files can be uploaded in the `rate_limit_period` time span.
  # Setting this to 0 disables rate limits, regardless if rate limits
  # are enabled.
  files_per_ip: 32
  # After 600 seconds, the limits for a specific IP will be lifted and
  # that IP address will be able to upload files again.
  rate_limit_period: 600

# Upload related settings
uploads:
  # Length of the filename that is going to be generated
  filename_length: 5
  # Max length of the filename, this is going to be max value
  # that can be set in the user settings ("/-/settings")
  max_filename_length: 16
  # Min length of the filename, this is going to be max value
  # that can be set in the user settings ("/-/settings")
  min_filename_length: 5
  # File size limit in MiB
  size_limit: 512
  # Enable checksumming of files, it uses the SHA1 hashing algorithm
  # and the computed hash will be used for ETag headers.
  enable_checksums: false
  # Blocked extensions that are not allowed to be uploaded to the server
  blocked_extensions:
    - "exe"
  # Deletion options
  deletion:
    # In hours (168 = 7 days)
    delete_files_after: 168
    # In seconds
    delete_files_check: 1800
    delete_key_length: 4
  magic_bytes:
    # How many bytes of the uploaded file should be thrown into the buffer
    # so libmagic can detect it's MIME type and extension.
    # 1024 bytes is the recommended value. Lowering this value may
    # reduce the precision of the guessed MIME type and extension.
    #
    # You shouldn't change this value, unless you know what you are doing!
    buffer_size: 131072

# http server
server:
  port: 8080
  host: 0.0.0.0
  # Tell search engines you don't wanna be indexed
  no_robots: false
  # Enabling the unix socket will disable port binding
  #unix_socket: "/tmp/patchy.sock"

# CORS: Cross-Origin Resource Sharing
# Will allow external websites from loading files from the domain Patchy is
# being hosted.
cors:
  enabled: false
  # Advanced options! You shouldn't change those unless you really want or need
  # to modify them.
  #
  # Paths to apply OPTIONS for CORS
  paths:
    - "/-/file/:filename"
    - "/-/thumbnail/:thumbnail"
    - "/upload"
    - "/-/upload"
  # This are the values that are going to be used on
  # Access-Control headers.
  access_control:
    allow_origin: "*"
    allow_methods: "GET, HEAD, POST, OPTIONS"
    allow_headers: "Content-Type"
    max_age: "3600"

# Enables thumbnail generation for programs that support OpenGraph tags
# WARNING: DO NOT ENABLE THIS IF YOU DON'T HAVE A HARDENED FFMPEG BUILD
# READ MORE ABOUT IT HERE:
# https://codeberg.org/Fijxu/patchy/src/branch/master/docs/security/ffmpeg.md
thumbnail_generation:
  enabled: false
  # Generate thumbnails in the background instead of processing them when the
  # file is being processed for upload. This saves time when uploading files
  # as it takes some time (around ~100ms more, depends of the file)
  # to process the thumbnail.
  # When having background generation enabled, the thumbnail will generate
  # right after the file has been uploaded.
  background_generation: false
  # When a file has no thumbnail, it will show a fallback thumbnail located in
  # ./public/-/assets/img/nothumbnail.jpg, it can be easily replaced by adding
  # an image file to ./public/-/assets/img/
  fallback_thumbnail:
    enabled: true
    thumbnail_file: "nothumbnail.jpg"
  resolution:
    max_height: 720
    max_width: 720

# To restrict Tor exit nodes and VPN providers IP addresses from uploading
# content to the uploader. Sometimes they can be an annoyance, legally speaking.
ip_block:
  tor:
    enabled: false
    update_interval: 3600
  vpn:
    enabled: false
    update_interval: 86400
    # Providers supported:
    # "Mullvad", "AirVPN"
    providers: []

admin:
  enabled: false
  api_key: "asd"

# S3 Support to upload the files to a S3 bucket.
# Thumbnail generation will not run when using a S3 bucket
s3:
  enabled: false
  # Ignored if is not AWS
  region: us-east-1
  key: "key"
  secret: "secret"
  endpoint: "https://someendpoint.example"

# Uses more memory, but improves files retrieval and reduces stress on the drive
cache:
  enabled: false
  # Type of cache
  # This can be LRU (Least Recently Used) or a Redis compatible database.
  # LRU is recommended, but if you are using a distributed Patchy setup, Redis
  # may be a better option to share the cache across different Patchy processes.
  # types: "lru", "redis"
  type: "lru"
  # The redis URL to connect to the Redis compatible database.
  # Example: "tcp://127.0.0.1:6379"
  # If it's empty, it will default to "localhost:6379"
  redis_url: ""

  # seconds, nil by default.
  expire_time: 3600
  # In KiB, files bigger than this will not be cached
  max_allowed_filesize: 512
  # Number of files that can be cached (LRU ONLY)
  max_size: 256
  # seconds, nil by default. (LRU ONLY)
  clean_interval: 60

# Modify what is shown on the different pages
views:
  index:
    site_info: "Welcome to Patchy - A temporary file uploader"
    show_title: true
    show_file_count: true
    show_version: true
    navbar:
      enabled: true
      show_uploader_configs: true
      show_upload_history: true
      show_admin: true
      show_login: true
  show_file:
    autoplay_video: false
    autoplay_audio: false

# Will display an abuse email contact link
# To disable, set it to empty (`""`)
# abuse_email: ""
abuse_email: "example@example.com"

# alternative_domains:
#   - "example.com"

# Advanced options that you shouldn't touch
# but you can touch them if you really need it.
advanced:
  # Calls the GC.collect method, frees memory every <interval> seconds
  # as Crystal by default frees memory when there is activity
  # https://crystal-lang.org/api/1.19.1/GC.html#collect-class-method
  gc:
    enabled: true
    interval: 10
